### ISSUE TITLE
Syntax error after installation

### ISSUE THREAD

**Issue by nesar** [andikisare/imgmarker#1]
After pip installation, I try running `imgmarker` from a directory, and I get this error. 

```
Traceback (most recent call last):
  File "/Users/nesar/anaconda3/envs/llm_env/bin/imgmarker", line 5, in <module>
    from imgmarker.__init__ import main
  File "/Users/nesar/Projects/HEP/IMGmarker/imgmarker/imgmarker/__init__.py", line 16, in <module>
    from imgmarker.window import MainWindow
  File "/Users/nesar/Projects/HEP/IMGmarker/imgmarker/imgmarker/window.py", line 216
    text += f'{'Keybindings':^{fullw_text}}\n'
                ^^^^^^^^^^^
SyntaxError: f-string: expecting '}'
```

Issue could be possibly resolved with `text += f"{'Keybindings':^{fullw_text}}\n"`

**Comment by astrorya** [comment]
What version of Python is installed in your environment? I'm guessing that this may have happened for you but not for us because of a version difference. Let me know and, if you're using a different version, I'll make an environment with the same version as you're using to test and fix this. Thanks!
